version: '3.5'

services:
  langfuse-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=langfuse
    ports:
      - "5432:5432"
    volumes:
      - langfuse_db_data:/var/lib/postgresql/data

  langfuse:
    # Cambiamos 'latest' por '2' para evitar el requisito de Clickhouse
    image: langfuse/langfuse:2
    depends_on:
      - langfuse-db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - DATABASE_URL=postgresql://postgres:postgres@langfuse-db:5432/langfuse
      - TELEMETRY_ENABLED=false

volumes:
  langfuse_db_data: